import { google, type drive_v3 } from "googleapis";
import { readFileSync } from "node:fs";
import { Readable } from "node:stream";

// ── Constants ──────────────────────────────────────────────────────────────────

/** AppProperties key used to tag files generated by the document service */
export const GENERATED_APP_PROPERTY_KEY = "generatedBy";
export const GENERATED_APP_PROPERTY_VALUE = "openclaw-document-service";

// ── Auth ───────────────────────────────────────────────────────────────────────

let cachedDrive: drive_v3.Drive | null = null;

interface ServiceAccountKey {
  client_email: string;
  private_key: string;
  [key: string]: unknown;
}

function getServiceAccountCredentials(): ServiceAccountKey {
  // Try inline JSON (plain or base64-encoded)
  const inline = process.env.GOOGLE_SERVICE_ACCOUNT_JSON;
  if (inline) {
    const trimmed = inline.trim();
    // If it starts with '{', it's plain JSON; otherwise assume base64
    const json = trimmed.startsWith("{")
      ? trimmed
      : Buffer.from(trimmed, "base64").toString("utf-8");
    return JSON.parse(json) as ServiceAccountKey;
  }

  // Try file path
  const filePath = process.env.GOOGLE_SERVICE_ACCOUNT_FILE;
  if (filePath) {
    const raw = readFileSync(filePath, "utf-8");
    return JSON.parse(raw) as ServiceAccountKey;
  }

  throw new Error(
    "Google Drive not configured: set GOOGLE_SERVICE_ACCOUNT_JSON (plain or base64) or GOOGLE_SERVICE_ACCOUNT_FILE"
  );
}

/**
 * Get an authenticated Google Drive v3 client using service account credentials
 * with domain-wide delegation (impersonating GOOGLE_IMPERSONATE_EMAIL).
 * The client is cached for the process lifetime.
 */
function getDriveClient(): drive_v3.Drive {
  if (cachedDrive) return cachedDrive;

  const credentials = getServiceAccountCredentials();
  const impersonateEmail = process.env.GOOGLE_IMPERSONATE_EMAIL;

  const auth = new google.auth.JWT({
    email: credentials.client_email,
    key: credentials.private_key,
    scopes: ["https://www.googleapis.com/auth/drive"],
    subject: impersonateEmail || undefined,
  });

  cachedDrive = google.drive({ version: "v3", auth });
  return cachedDrive;
}

// ── Types ──────────────────────────────────────────────────────────────────────

export interface DriveFile {
  id: string;
  name: string;
  mimeType: string;
  modifiedTime: string;
  size?: string;
  webViewLink?: string;
  createdTime?: string;
  parents?: string[];
  /** App-specific metadata — used to distinguish generated vs. uploaded files */
  appProperties?: Record<string, string>;
}

export interface ListFilesOptions {
  folderId?: string;
  pageSize?: number;
  pageToken?: string;
  orderBy?: string;
  query?: string;
}

export interface ListFilesResult {
  files: DriveFile[];
  nextPageToken?: string;
}

// ── Helpers ────────────────────────────────────────────────────────────────────

const FILE_FIELDS = "id, name, mimeType, modifiedTime, size, webViewLink, createdTime, parents, appProperties";

/** Sanitize a value for use in a Drive API query string (escape backslashes then single quotes). */
function sanitizeDriveQuery(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/'/g, "\\'");
}

function mapFile(f: drive_v3.Schema$File): DriveFile {
  return {
    id: f.id ?? "",
    name: f.name ?? "Untitled",
    mimeType: f.mimeType ?? "application/octet-stream",
    modifiedTime: f.modifiedTime ?? new Date().toISOString(),
    size: f.size ?? undefined,
    webViewLink: f.webViewLink ?? undefined,
    createdTime: f.createdTime ?? undefined,
    parents: (f.parents as string[] | undefined) ?? undefined,
    appProperties: (f.appProperties as Record<string, string> | undefined) ?? undefined,
  };
}

// ── API Functions ──────────────────────────────────────────────────────────────

/**
 * List files in Google Drive with optional pagination, sorting, and filtering.
 */
export async function listFiles(options: ListFilesOptions = {}): Promise<ListFilesResult> {
  const drive = getDriveClient();
  const {
    folderId,
    pageSize = 100,
    pageToken,
    orderBy = "modifiedTime desc",
    query,
  } = options;

  let q = "trashed = false";
  if (folderId) {
    q += ` and '${sanitizeDriveQuery(folderId)}' in parents`;
  }
  if (query) {
    q += ` and ${query}`;
  }

  const res = await drive.files.list({
    q,
    pageSize,
    pageToken: pageToken ?? undefined,
    orderBy,
    fields: `nextPageToken, files(${FILE_FIELDS})`,
    supportsAllDrives: true,
    includeItemsFromAllDrives: true,
  });

  return {
    files: (res.data.files ?? []).map(mapFile),
    nextPageToken: res.data.nextPageToken ?? undefined,
  };
}

/**
 * Get file metadata by ID.
 */
export async function getFile(fileId: string): Promise<DriveFile> {
  const drive = getDriveClient();
  const res = await drive.files.get({
    fileId,
    fields: FILE_FIELDS,
    supportsAllDrives: true,
  });
  return mapFile(res.data);
}

/**
 * Upload a file to Google Drive.
 *
 * @param appProperties - Optional key/value metadata stored on the file.
 *   Use `{ [GENERATED_APP_PROPERTY_KEY]: GENERATED_APP_PROPERTY_VALUE }` to tag
 *   files generated by the document service so the Artifacts panel can separate them.
 */
export async function uploadFile(
  name: string,
  content: Buffer | Readable,
  mimeType: string,
  folderId?: string,
  appProperties?: Record<string, string>,
): Promise<DriveFile> {
  const drive = getDriveClient();

  const fileMetadata: drive_v3.Schema$File = { name };
  if (folderId) {
    fileMetadata.parents = [folderId];
  }
  if (appProperties && Object.keys(appProperties).length > 0) {
    fileMetadata.appProperties = appProperties;
  }

  const media = {
    mimeType,
    body: content instanceof Buffer ? Readable.from(content) : content,
  };

  const res = await drive.files.create({
    requestBody: fileMetadata,
    media,
    fields: FILE_FIELDS,
    supportsAllDrives: true,
  });

  return mapFile(res.data);
}

/**
 * Search files by name or full-text content.
 */
export async function searchFiles(
  searchQuery: string,
  pageSize = 50
): Promise<DriveFile[]> {
  const drive = getDriveClient();

  const sanitized = sanitizeDriveQuery(searchQuery);
  const q = `trashed = false and (name contains '${sanitized}' or fullText contains '${sanitized}')`;

  const res = await drive.files.list({
    q,
    pageSize,
    orderBy: "modifiedTime desc",
    fields: `files(${FILE_FIELDS})`,
    supportsAllDrives: true,
    includeItemsFromAllDrives: true,
  });

  return (res.data.files ?? []).map(mapFile);
}

/**
 * Share a file with a specific user or make it accessible to anyone with the link.
 *
 * - If `email` is provided, creates a user-targeted permission.
 * - If `email` is omitted, creates an "anyone with the link" permission (type=anyone).
 *
 * @param fileId  - Drive file ID to share.
 * @param role    - Permission role: "reader" or "writer". Defaults to "reader".
 * @param email   - Email address to grant access to. Omit for public link.
 * @returns       - The permission ID of the created permission.
 */
export async function shareFile(
  fileId: string,
  role: "reader" | "writer" = "reader",
  email?: string,
): Promise<string> {
  const drive = getDriveClient();

  const permissionBody: drive_v3.Schema$Permission = email
    ? { role, type: "user", emailAddress: email }
    : { role, type: "anyone" };

  const res = await drive.permissions.create({
    fileId,
    requestBody: permissionBody,
    fields: "id",
    supportsAllDrives: true,
    // Suppress Google's email notification (noise for automated sharing)
    sendNotificationEmail: Boolean(email),
  });

  return res.data.id ?? "";
}

/**
 * Get a shareable "anyone with the link" URL for a file.
 *
 * Ensures the file has an "anyone → reader" permission (creates it if absent),
 * then returns the webViewLink from the file's metadata.
 *
 * @param fileId - Drive file ID.
 * @returns      - The shareable `webViewLink` URL.
 */
export async function getShareLink(fileId: string): Promise<string> {
  // Ensure public read permission exists
  await shareFile(fileId, "reader");

  // Fetch the webViewLink — it's always populated for Drive files
  const file = await getFile(fileId);
  if (!file.webViewLink) {
    throw new Error(`File "${fileId}" has no webViewLink — cannot generate share link.`);
  }

  return file.webViewLink;
}

/**
 * Create a folder in Google Drive.
 *
 * @param name      - Display name of the folder.
 * @param parentId  - Parent folder ID. Omit to create in root.
 * @returns         - The created folder as a DriveFile.
 */
export async function createFolder(
  name: string,
  parentId?: string,
): Promise<DriveFile> {
  const drive = getDriveClient();

  const fileMetadata: drive_v3.Schema$File = {
    name,
    mimeType: "application/vnd.google-apps.folder",
  };
  if (parentId) {
    fileMetadata.parents = [parentId];
  }

  const res = await drive.files.create({
    requestBody: fileMetadata,
    fields: FILE_FIELDS,
    supportsAllDrives: true,
  });

  return mapFile(res.data);
}
