/** A file entry from the Google Drive API. */
export interface DriveFile {
  id: string;
  name: string;
  mimeType: string;
  modifiedTime: string;
  size?: string;
  webViewLink?: string;
  /** App-specific metadata — files generated by the document service have generatedBy="openclaw-document-service" */
  appProperties?: Record<string, string>;
}

/** Value used in appProperties.generatedBy for document-service files */
export const GENERATED_BY_VALUE = "openclaw-document-service";

export type SortDirection = "newest" | "oldest";
