// ─── Studio Task Types ───────────────────────────────────────────────────────
// These types represent the Studio-level task abstraction layered on top of
// OpenClaw cron jobs.  The Studio metadata (StudioTask) is persisted as a JSON
// file per agent while the underlying cron job lives in the gateway.

export type TaskType = "constant" | "periodic" | "scheduled";

// ─── Schedule variants ───────────────────────────────────────────────────────

export type ConstantSchedule = {
  type: "constant";
  /** Interval in milliseconds (e.g. 60000 = 1 min) */
  intervalMs: number;
  /** Optional active-hours window */
  activeHours?: { start: string; end: string; timezone: string };
  /** Random delay added to each fire time (ms). 0 = exact. */
  staggerMs?: number;
};

export type PeriodicSchedule = {
  type: "periodic";
  /** Interval in milliseconds (e.g. 900000 = 15 min) */
  intervalMs: number;
  /** Random delay added to each fire time (ms). 0 = exact. */
  staggerMs?: number;
};

export type ScheduledSchedule = {
  type: "scheduled";
  /** Days of week: 0=Sun … 6=Sat */
  days: number[];
  /** Times in HH:mm 24-h format */
  times: string[];
  /** IANA timezone */
  timezone: string;
};

export type TaskSchedule = ConstantSchedule | PeriodicSchedule | ScheduledSchedule;

// ─── StudioTask ──────────────────────────────────────────────────────────────

export interface StudioTask {
  id: string;
  cronJobId: string;
  agentId: string;

  // User-facing
  name: string;
  description: string;
  type: TaskType;

  // Schedule
  schedule: TaskSchedule;

  // Execution
  prompt: string;
  model: string;
  /** Thinking level for the model (e.g. "low", "medium", "high") */
  thinking: string | null;
  deliveryChannel: string | null;
  deliveryTarget: string | null;

  // State
  enabled: boolean;
  createdAt: string;
  updatedAt: string;
  lastRunAt: string | null;
  lastRunStatus: "success" | "error" | null;
  runCount: number;

  // Runtime state (enriched from cron, not persisted)
  nextRunAtMs?: number;
  runningAtMs?: number;
  lastDurationMs?: number;
  consecutiveErrors?: number;
}

// ─── API payloads ────────────────────────────────────────────────────────────

export interface CreateTaskPayload {
  agentId: string;
  name: string;
  description: string;
  type: TaskType;
  schedule: TaskSchedule;
  prompt: string;
  model: string;
  thinking?: string | null;
  deliveryChannel?: string | null;
  deliveryTarget?: string | null;
}

/**
 * Payload for updating a task's UI metadata in the Studio DB.
 *
 * NOTE: `schedule` and `enabled` are NOT included — they are cron-owned fields.
 * Schedule changes go directly to gateway cron via `updateCronJob()`.
 * Enable/disable goes to cron via `updateCronJob()`.
 * The enrichment layer reads them back from cron at load time.
 */
export interface UpdateTaskPayload {
  name?: string;
  description?: string;
  prompt?: string;
  model?: string;
  thinking?: string | null;
  deliveryChannel?: string | null;
  deliveryTarget?: string | null;
}

// ─── Wizard types ────────────────────────────────────────────────────────────

export interface WizardMessage {
  role: "user" | "assistant";
  content: string;
}

/** Structured task config generated by the wizard AI */
export interface WizardTaskConfig {
  name: string;
  description: string;
  type: TaskType;
  schedule: TaskSchedule;
  prompt: string;
  model: string;
  thinking?: string | null;
  agentId: string;
  deliveryChannel?: string | null;
}

// ─── Thinking level options ───────────────────────────────────────────────────

export const THINKING_OPTIONS = [
  { label: "Off", value: "" },
  { label: "Low", value: "low" },
  { label: "Medium", value: "medium" },
  { label: "High", value: "high" },
] as const;

// ─── Delivery mode options ───────────────────────────────────────────────────

export const DELIVERY_MODE_OPTIONS = [
  { label: "Announce", value: "announce" },
  { label: "None", value: "none" },
] as const;

// ─── Stagger options ─────────────────────────────────────────────────────────

export const STAGGER_OPTIONS = [
  { label: "Exact", ms: 0 },
  { label: "±1 min", ms: 60_000 },
  { label: "±5 min", ms: 300_000 },
  { label: "±10 min", ms: 600_000 },
  { label: "±20 min", ms: 1_200_000 },
  { label: "±30 min", ms: 1_800_000 },
] as const;

// ─── Constants ───────────────────────────────────────────────────────────────

export const CONSTANT_INTERVAL_OPTIONS = [
  { label: "Every 1 min", ms: 60_000 },
  { label: "Every 2 min", ms: 120_000 },
  { label: "Every 5 min", ms: 300_000 },
] as const;

export const PERIODIC_INTERVAL_OPTIONS = [
  { label: "Every 5 min", ms: 300_000 },
  { label: "Every 10 min", ms: 600_000 },
  { label: "Every 15 min", ms: 900_000 },
  { label: "Every 30 min", ms: 1_800_000 },
  { label: "Every 1 hour", ms: 3_600_000 },
  { label: "Every 2 hours", ms: 7_200_000 },
  { label: "Every 4 hours", ms: 14_400_000 },
  { label: "Every 8 hours", ms: 28_800_000 },
  { label: "Every 12 hours", ms: 43_200_000 },
  { label: "Every 24 hours", ms: 86_400_000 },
] as const;
