// ─── Studio Task Types ───────────────────────────────────────────────────────
// These types represent the Studio-level task abstraction layered on top of
// OpenClaw cron jobs.  The Studio metadata (StudioTask) is persisted as a JSON
// file per agent while the underlying cron job lives in the gateway.

export type TaskType = "constant" | "periodic" | "scheduled";

// ─── Schedule variants ───────────────────────────────────────────────────────

export type ConstantSchedule = {
  type: "constant";
  /** Interval in milliseconds (e.g. 60000 = 1 min) */
  intervalMs: number;
  /** Optional active-hours window */
  activeHours?: { start: string; end: string; timezone: string };
};

export type PeriodicSchedule = {
  type: "periodic";
  /** Interval in milliseconds (e.g. 900000 = 15 min) */
  intervalMs: number;
};

export type ScheduledSchedule = {
  type: "scheduled";
  /** Days of week: 0=Sun … 6=Sat */
  days: number[];
  /** Times in HH:mm 24-h format */
  times: string[];
  /** IANA timezone */
  timezone: string;
};

export type TaskSchedule = ConstantSchedule | PeriodicSchedule | ScheduledSchedule;

// ─── StudioTask ──────────────────────────────────────────────────────────────

export interface StudioTask {
  id: string;
  cronJobId: string;
  agentId: string;

  // User-facing
  name: string;
  description: string;
  type: TaskType;

  // Schedule
  schedule: TaskSchedule;

  // Execution
  prompt: string;
  model: string;
  deliveryChannel: string | null;
  deliveryTarget: string | null;

  // State
  enabled: boolean;
  createdAt: string;
  updatedAt: string;
  lastRunAt: string | null;
  lastRunStatus: "success" | "error" | null;
  runCount: number;

  // Runtime state (enriched from cron, not persisted)
  nextRunAtMs?: number;
  runningAtMs?: number;
  lastDurationMs?: number;
  consecutiveErrors?: number;
}

// ─── API payloads ────────────────────────────────────────────────────────────

export interface CreateTaskPayload {
  agentId: string;
  name: string;
  description: string;
  type: TaskType;
  schedule: TaskSchedule;
  prompt: string;
  model: string;
  deliveryChannel?: string | null;
  deliveryTarget?: string | null;
}

export interface UpdateTaskPayload {
  name?: string;
  description?: string;
  schedule?: TaskSchedule;
  prompt?: string;
  model?: string;
  enabled?: boolean;
  deliveryChannel?: string | null;
  deliveryTarget?: string | null;
}

// ─── Wizard types ────────────────────────────────────────────────────────────

export interface WizardMessage {
  role: "user" | "assistant";
  content: string;
}

/** Structured task config generated by the wizard AI */
export interface WizardTaskConfig {
  name: string;
  description: string;
  type: TaskType;
  schedule: TaskSchedule;
  prompt: string;
  model: string;
  agentId: string;
  deliveryChannel?: string | null;
}

// ─── Constants ───────────────────────────────────────────────────────────────

export const CONSTANT_INTERVAL_OPTIONS = [
  { label: "Every 1 min", ms: 60_000 },
  { label: "Every 2 min", ms: 120_000 },
  { label: "Every 5 min", ms: 300_000 },
] as const;

export const PERIODIC_INTERVAL_OPTIONS = [
  { label: "Every 5 min", ms: 300_000 },
  { label: "Every 10 min", ms: 600_000 },
  { label: "Every 15 min", ms: 900_000 },
  { label: "Every 30 min", ms: 1_800_000 },
  { label: "Every 1 hour", ms: 3_600_000 },
  { label: "Every 2 hours", ms: 7_200_000 },
  { label: "Every 4 hours", ms: 14_400_000 },
  { label: "Every 8 hours", ms: 28_800_000 },
  { label: "Every 12 hours", ms: 43_200_000 },
  { label: "Every 24 hours", ms: 86_400_000 },
] as const;
