/**
 * build-templates.ts — Persona Template Registry Build Script
 *
 * Scans each template subdirectory under src/features/personas/templates/,
 * validates the shape of template.ts in each, then regenerates
 * generatedTemplates.ts with the complete ordered list.
 *
 * Usage:
 *   node scripts/build-templates.ts [--dry-run] [--validate-only]
 *
 * Flags:
 *   --dry-run        Print what would be written without writing
 *   --validate-only  Validate templates without regenerating the output file
 */

import fs from "node:fs";
import path from "node:path";

// ---------------------------------------------------------------------------
// Config
// ---------------------------------------------------------------------------

const ROOT = path.resolve(process.cwd());
const TEMPLATES_DIR = path.join(ROOT, "src/features/personas/templates");
const OUTPUT_FILE = path.join(ROOT, "src/features/personas/lib/generatedTemplates.ts");

const REQUIRED_TOP_LEVEL_KEYS = [
  "key",
  "name",
  "description",
  "longDescription",
  "category",
  "icon",
  "tags",
  "placeholders",
  "discoveryPhases",
  "practiceModeType",
  "scoringDimensions",
  "skillRequirements",
  "brainFileTemplates",
  "knowledgeFileTemplates",
  "estimatedSetupMinutes",
  "difficulty",
] as const;

const VALID_CATEGORIES = new Set([
  "sales",
  "admin",
  "support",
  "marketing",
  "hr",
  "finance",
  "legal",
  "operations",
]);

// ---------------------------------------------------------------------------
// Args
// ---------------------------------------------------------------------------

const args = process.argv.slice(2);
const DRY_RUN = args.includes("--dry-run");
const VALIDATE_ONLY = args.includes("--validate-only");

// ---------------------------------------------------------------------------
// Discovery
// ---------------------------------------------------------------------------

interface TemplateEntry {
  key: string;
  exportName: string;
  importPath: string;
}

function discoverTemplates(): TemplateEntry[] {
  const entries: TemplateEntry[] = [];

  const subdirs = fs
    .readdirSync(TEMPLATES_DIR, { withFileTypes: true })
    .filter((d) => d.isDirectory() && !d.name.startsWith("_") && !d.name.startsWith("."));

  for (const dir of subdirs) {
    const templateFile = path.join(TEMPLATES_DIR, dir.name, "template.ts");
    if (!fs.existsSync(templateFile)) {
      console.warn(`⚠️  Skipping ${dir.name}/ — no template.ts found`);
      continue;
    }

    // Derive export name from directory name (kebab → camelCase + "Template")
    const camel = dir.name
      .split("-")
      .map((part, i) => (i === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1)))
      .join("");
    const exportName = `${camel}Template`;

    // Relative import path for generated file
    const importPath = `../templates/${dir.name}/template`;

    entries.push({ key: dir.name, exportName, importPath });
  }

  // Sort by key for deterministic output
  entries.sort((a, b) => a.key.localeCompare(b.key));

  return entries;
}

// ---------------------------------------------------------------------------
// Generate output
// ---------------------------------------------------------------------------

function generateOutput(entries: TemplateEntry[]): string {
  const imports = entries
    .map((e) => `import { ${e.exportName} } from "${e.importPath}";`)
    .join("\n");

  const arrayEntries = entries.map((e) => `  ${e.exportName},`).join("\n");

  return `/**
 * Generated Template Registry — static array of all compiled Starter Kit templates.
 *
 * ⚠️  Do NOT import this from template modules — only from templateRegistry.ts.
 *     Do NOT hand-edit template data here; edit the source in templates/<key>/template.ts
 *     and run \`npm run build:templates\` to regenerate.
 *
 * Generated by: scripts/build-templates.ts
 * Generated at: ${new Date().toISOString()}
 * Template count: ${entries.length}
 */

${imports}
import type { PersonaTemplate } from "./templateTypes";

/**
 * All registered Starter Kit templates in alphabetical key order.
 * Order can be customized by editing scripts/build-templates.ts.
 */
export const PERSONA_TEMPLATES: PersonaTemplate[] = [
${arrayEntries}
];
`;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function main(): void {
  console.log("🔍  Scanning template directory...");

  const entries = discoverTemplates();
  console.log(`   Found ${entries.length} template(s): ${entries.map((e) => e.key).join(", ")}`);

  // Validate each template by reading its file and checking structure
  let hasErrors = false;

  for (const entry of entries) {
    const filePath = path.join(TEMPLATES_DIR, entry.key, "template.ts");
    const source = fs.readFileSync(filePath, "utf8");

    // Basic structural checks via regex — full type checking is done by tsc
    const errors: string[] = [];

    // Check export name matches expected
    if (!source.includes(`export const ${entry.exportName}`)) {
      errors.push(`Expected export named '${entry.exportName}' but not found`);
    }

    // Check required fields appear in source
    for (const field of REQUIRED_TOP_LEVEL_KEYS) {
      const fieldRegex = new RegExp(`\\b${field}\\s*:`);
      if (!fieldRegex.test(source)) {
        errors.push(`Missing required field: ${field}`);
      }
    }

    // Check key matches dir name
    const keyMatch = source.match(/\bkey\s*:\s*["']([^"']+)["']/);
    if (keyMatch && keyMatch[1] !== entry.key) {
      errors.push(`'key' ("${keyMatch[1]}") must match directory name ("${entry.key}")`);
    }

    // Check category is valid
    const categoryMatch = source.match(/\bcategory\s*:\s*["']([^"']+)["']/);
    if (categoryMatch && !VALID_CATEGORIES.has(categoryMatch[1])) {
      errors.push(`'category' ("${categoryMatch[1]}") is not a valid PersonaCategory`);
    }

    // Check SOUL.md and AGENTS.md are present in brainFileTemplates
    if (!source.includes('"SOUL.md"') && !source.includes("'SOUL.md'")) {
      errors.push("'brainFileTemplates' must include a SOUL.md entry");
    }
    if (!source.includes('"AGENTS.md"') && !source.includes("'AGENTS.md'")) {
      errors.push("'brainFileTemplates' must include an AGENTS.md entry");
    }

    if (errors.length > 0) {
      hasErrors = true;
      const rel = path.relative(ROOT, filePath);
      console.error(`\n❌  ${rel}`);
      errors.forEach((e) => console.error(`   • ${e}`));
    } else {
      console.log(`   ✅  ${entry.key}`);
    }

  }

  if (hasErrors) {
    console.error("\n💥  Validation failed. Fix the errors above before regenerating.\n");
    process.exit(1);
  }

  if (VALIDATE_ONLY) {
    console.log("\n✅  All templates valid (--validate-only, skipping code generation).\n");
    return;
  }

  // Generate output
  const output = generateOutput(entries);

  if (DRY_RUN) {
    console.log("\n--- DRY RUN: would write to", path.relative(ROOT, OUTPUT_FILE), "---\n");
    console.log(output);
    return;
  }

  fs.writeFileSync(OUTPUT_FILE, output, "utf8");
  console.log(`\n✅  Wrote ${entries.length} template(s) → ${path.relative(ROOT, OUTPUT_FILE)}\n`);
}

main();
