/**
 * Generated Template Registry — static array of all compiled Starter Kit templates.
 *
 * ⚠️  Do NOT import this from template modules — only from templateRegistry.ts.
 *     Do NOT hand-edit template data here; edit the source in templates/<key>/template.ts
 *     and run `npm run build:templates` to regenerate.
 *
 * Generated by: scripts/build-templates.ts
 * Generated at: 2026-03-01T05:41:24.309Z
 * Template count: 4
 */

import { coldCallerTemplate } from "../templates/cold-caller/template";
import { contentWriterTemplate } from "../templates/content-writer/template";
import { executiveAssistantTemplate } from "../templates/executive-assistant/template";
import { itHelpdeskTemplate } from "../templates/it-helpdesk/template";
import type { PersonaTemplate } from "./templateTypes";

/**
 * All registered Starter Kit templates in alphabetical key order.
 * Order can be customized by editing scripts/build-templates.ts.
 */
export const PERSONA_TEMPLATES: PersonaTemplate[] = [
  coldCallerTemplate,
  contentWriterTemplate,
  executiveAssistantTemplate,
  itHelpdeskTemplate,
];
