/**
 * Generated Template Registry — static array of all compiled Starter Kit templates.
 *
 * ⚠️  Do NOT import this from template modules — only from templateRegistry.ts.
 *     Do NOT hand-edit template data here; edit the source in templates/<key>/template.ts
 *     and run `npm run build:templates` to regenerate.
 *
 * Generated by: scripts/build-templates.ts
 */

import { coldCallerTemplate } from "../templates/cold-caller/template";
import { executiveAssistantTemplate } from "../templates/executive-assistant/template";
import type { PersonaTemplate } from "./templateTypes";

/**
 * All registered Starter Kit templates in display order.
 * Order matters — first entry appears first in the browser.
 */
export const PERSONA_TEMPLATES: PersonaTemplate[] = [
  executiveAssistantTemplate,
  coldCallerTemplate,
];
