/**
 * Generated Template Registry — static array of all compiled Starter Kit templates.
 *
 * ⚠️  Do NOT import this from template modules — only from templateRegistry.ts.
 *     Do NOT hand-edit template data here; edit the source in templates/<key>/template.ts
 *     and run `npm run build:templates` to regenerate.
 *
 * Generated by: scripts/build-templates.ts
 * Generated at: 2026-03-04T19:06:37.030Z
 * Template count: 24
 */

import { accountExecutiveTemplate } from "../templates/account-executive/template";
import { bookkeeperTemplate } from "../templates/bookkeeper/template";
import { coldCallerTemplate } from "../templates/cold-caller/template";
import { complianceMonitorTemplate } from "../templates/compliance-monitor/template";
import { contentWriterTemplate } from "../templates/content-writer/template";
import { customerServiceRepTemplate } from "../templates/customer-service-rep/template";
import { customerSuccessManagerTemplate } from "../templates/customer-success-manager/template";
import { devopsSpecialistTemplate } from "../templates/devops-specialist/template";
import { emailMarketerTemplate } from "../templates/email-marketer/template";
import { executiveAssistantTemplate } from "../templates/executive-assistant/template";
import { financialAnalystTemplate } from "../templates/financial-analyst/template";
import { hrOperationsTemplate } from "../templates/hr-operations/template";
import { interviewCoordinatorTemplate } from "../templates/interview-coordinator/template";
import { itHelpdeskTemplate } from "../templates/it-helpdesk/template";
import { leadQualifierTemplate } from "../templates/lead-qualifier/template";
import { legalResearcherTemplate } from "../templates/legal-researcher/template";
import { marketResearcherTemplate } from "../templates/market-researcher/template";
import { officeAdminTemplate } from "../templates/office-admin/template";
import { procurementSpecialistTemplate } from "../templates/procurement-specialist/template";
import { projectCoordinatorTemplate } from "../templates/project-coordinator/template";
import { recruiterTemplate } from "../templates/recruiter/template";
import { salesOpsTemplate } from "../templates/sales-ops/template";
import { securityAnalystTemplate } from "../templates/security-analyst/template";
import { technicalSupportTemplate } from "../templates/technical-support/template";
import type { PersonaTemplate } from "./templateTypes";

/**
 * All registered Starter Kit templates in alphabetical key order.
 * Order can be customized by editing scripts/build-templates.ts.
 */
export const PERSONA_TEMPLATES: PersonaTemplate[] = [
  accountExecutiveTemplate,
  bookkeeperTemplate,
  coldCallerTemplate,
  complianceMonitorTemplate,
  contentWriterTemplate,
  customerServiceRepTemplate,
  customerSuccessManagerTemplate,
  devopsSpecialistTemplate,
  emailMarketerTemplate,
  executiveAssistantTemplate,
  financialAnalystTemplate,
  hrOperationsTemplate,
  interviewCoordinatorTemplate,
  itHelpdeskTemplate,
  leadQualifierTemplate,
  legalResearcherTemplate,
  marketResearcherTemplate,
  officeAdminTemplate,
  procurementSpecialistTemplate,
  projectCoordinatorTemplate,
  recruiterTemplate,
  salesOpsTemplate,
  securityAnalystTemplate,
  technicalSupportTemplate,
];
